name: vercye
channels:
  - conda-forge
  - bioconda
  - pytorch
  - defaults

dependencies:
  - python=3.12
  - gdal=3.11
  - click
  - cairo
  - colorlog
  - geopandas
  - joblib
  - matplotlib
  - numpy
  - pandas
  - pathvalidate
  - pillow
  - planetary-computer
  - plotly=6
  - pystac-client
  - pyarrow
  - pycairo
  - rasterio
  - requests
  - ruamel.yaml
  - scipy>=1.14
  - scikit-learn
  - seaborn
  - snakemake
  - tenacity
  - pytorch
  - tqdm
  - xhtml2pdf
  - jq
  - pip
  - pip:
      - kaleido==0.2.1
      - STAC-Downloader @ git+https://github.com/rohansaw/STAC-Downloader
