date_ranges:
  - start_date: "2019-04-01"
    end_date: "2019-06-30"
  - start_date: "2020-03-15"
    end_date: "2020-07-15"
  - start_date: "2021-05-01"
    end_date: "2021-09-30"
  
resolution: 20
geojson_path: region.geojson
out_dir: output
region_out_prefix: "myregion"
from_step: 0
num_cores: 64
chunk_days: 30