# type: ignore  # Prevent issues with auto-linting snakefiles

import os
from pathlib import Path
import os.path as op

# Get list of region names from geojson files
def get_regions():
    geojsons_dir = config['geojsons_dir']
    return [Path(f).stem for f in os.listdir(geojsons_dir) if f.endswith('.geojson')]

# Define final output targets
rule all:
    input:
        lai_outputs = [
                f"logs/estimate_lai_{region}_{config['timepoints'][timepoint]['start_date']}__{config['timepoints'][timepoint]['end_date']}_done.txt"
                for timepoint in config["timepoints"]
                for region in get_regions()
            ],
        merged_lai_outputs = [
            f"logs/merge_lai_{config['timepoints'][timepoint]['start_date']}__{config['timepoints'][timepoint]['end_date']}_done.txt"
            for timepoint in config["timepoints"]
        ]


# Rule to export Sentinel-2 data from GEE to Google Drive and download it automatically
rule download_rs_data_STAC:
    input:
        lambda wildcards: os.path.join(config['geojsons_dir'], f"{wildcards.region_name}.geojson")
    params:
        library = config['geojsons_dir'],
        resolution = config['resolution'],
        local_storage_dir = os.path.join(config['output_base_dir'], 'stac_tiles'),
    output:
        "logs/stac_export_{region_name}_{start_date}__{end_date}_done.txt"
    threads:
        workflow.cores * 0.75 # Limit to one job at a time due to internatl parallelism of the job
    shell:
        """
        mkdir -p {params.local_storage_dir} \
        && python 1_1_gee_export_S2.py --project {params.ee_project} --library {params.library} --region {wildcards.region_name} \
        --start-date "{wildcards.start_date}" --end-date "{wildcards.end_date}" --resolution {params.resolution} \
        --gdrive-credentials {params.gdrive_credentials_path} --download-folder {params.local_storage_dir} && touch {output}
        """

# Rule to estimate LAI from the standardized Sentinel-2 data
rule estimate_lai:
    input:
        all_regions = lambda wildcards: expand('logs/stac_export_{region_name}_{start_date}__{end_date}_done.txt',
            region_name=get_regions(),
            start_date=wildcards.start_date,
            end_date=wildcards.end_date
        )
    params:
        resolution = config['resolution'],
        input_dir = op.join(config['output_base_dir'], 'stac_tiles'),
        lai_dir = op.join(config['output_base_dir'], 'lai'),
    output:
        'logs/estimate_lai_{start_date}__{end_date}_done.txt'
    shell:
        """
        mkdir -p {params.lai_dir} \
        && python 2_1_primary_LAI_tiled.py {params.input_dir} {params.lai_dir} {params.resolution} --start_date {wildcards.start_date} --end_date {wildcards.end_date} \
        && touch {output}
        """

# Rule to merge LAI estimates for all regions into daily VRTs
rule merge_lai:
    input:
        all_regions = lambda wildcards: expand('logs/estimate_lai_{region_name}_{start_date}__{end_date}_done.txt', 
            region_name=get_regions(),
            start_date=wildcards.start_date,
            end_date=wildcards.end_date

        )
    params:
        lai_dir = op.join(config['output_base_dir'], 'lai'),
        output_dir = op.join(config['output_base_dir'], 'merged_lai'),
        resolution = config['resolution'],
        region_out_prefix = config['combined_region_name'],  
    output:
        'logs/merge_lai_{start_date}__{end_date}_done.txt'
    shell:
        """
        mkdir -p {params.output_dir} \
        && python 2_2_build_daily_vrts.py {params.lai_dir} {params.output_dir} {params.resolution} --start-date {wildcards.start_date} --end-date {wildcards.end_date} --region-out-prefix region_out_prefix \
        && touch {output}
        """