name: Feature Request
description: Propose a new feature or enhancement
title: "[FEATURE] "
labels: enhancement

body:
  - type: markdown
    attributes:
      value: |
        Propose a new feature. Please provide detailed context and benefits.
  - type: textarea
    attributes:
      label: Feature description
      description: Briefly describe the feature or enhancement and the underlying problem.
      placeholder: "Feature description..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested solution
      description: Describe your proposed solution or implementation if known.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the feature request.
