cores: 110
retries: 3
resources:
  - nasa_power_calls=5
  - era5_calls=10
  - kaleido_resources=5

# Might want to add the apsim limitations and match_sim to this aswell
# Need to experiment with these values