# Params for step1
geojsons_dir: 'lai/regions/'
ee_project: 'ee-project-id'
timepoints:
  2024:
    start_date: '2024-10-10'
    end_date: '2025-04-03'
resolution: 20

# Params for step2
output_base_dir: 'outputdir'
gdrive_credentials_path: '/path/to/credentials.json'
gdrive_folders:
  el_hajeb: 'abcde'
  taounate: 'cdefgh
  settat: 'ijklmnop'