# Params for step1
geojsons_dir: '/gpfs/data1/cmongp2/sawahnr/data/morocco/Geo2MA1994_Regions/LAI_Regions/2024-25-cropland-ge-5percent'
ee_project: 'bsos-geog-harvest-raaps'
timepoints:
  2024:
      start_date: '2024-10-10'
      end_date: '2025-04-17'
resolution: 20

# Params for step2
output_base_dir: '/gpfs/data1/cmongp2/sawahnr/data/morocco/Geo2MA1994_Regions'
gdrive_credentials_path: '/home/sawahnr/rohan-gdrive-client.json'
gdrive_folders:
  abc: 'abc'