########################################
# Platform
platform: 'local'

########################################
# Simulation Parameters

# Directory containing each region. Update this for each new snakemake run
sim_study_head_dir: '/path/to/desired/simstudy/dir'

# Specify one or more simulations
regions:
  - 'Poltava'

sim_start_date: '2024-03-01'
sim_end_date: '2024-09-30'
nasa_power_start_date: '1994-01-01'
nasa_power_end_date: '2024-03-31'
  
########################################
# Local paths to the python/APSIM scripts

# UPDATE BELOW ONE TIME to set the paths to scripts in this directory
scripts:
  construct_met_files: '/path/to/vercye_ops/vercye_ops/apsim/construct_met_files.py'
  fetch_met_data: '/path/to/vercye_ops/vercye_ops/apsim/fetch_met_data.py'
  update_apsimx_template: '/path/to/vercye_ops/vercye_ops/apsim/update_apsimx_template.py'