site_name: VeRCYE Documentation
theme:
  name: material
  language: en
  features:
    - navigation.tracking
    - toc.integrate
    - search.suggest
    - search.highlight

nav:
  - 'Home': 'index.md'
  - 'Vercye Pipeline':
    - 'Running VeRCYe':
      - 'CLI': 'Vercye/cli.md'
      - 'Manual execution': 'Vercye/running.md'
      - 'Troubleshooting': 'Vercye/troubleshooting.md'
      - 'Inputs': 'Vercye/inputs.md'
      - 'Outputs': 'Vercye/outputs.md'
    - 'Meteorological Data': 'Vercye/metdata.md'
    - 'Vercye Library Architecture': 'Vercye/architecture.md'
    - 'APSIMX': 'Vercye/apsim.md'
  - 'LAI Pipeline':
    - 'Introduction': 'LAI/intro.md'
    - 'Generating LAI Data': 'LAI/running.md'
    - 'GEE Pipeline Architecture': 'LAI/gee_architecture.md'
    - 'STAC Pipeline Architecture': 'LAI/stac_architecture.md'
  - 'Vercye Webapp': 'Vercye/webapp.md'

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2

plugins:
  - search