site_name: VeRCYE Documentation
theme:
  name: material
  language: en
  features:
    - navigation.tracking
    - toc.integrate

nav:
  - 'Home': 'index.md'
  - 'Vercye':
    - 'Getting Started': 'Vercye/intro.md'
    - 'Inputs': 'Vercye/inputs.md'
    - 'Outputs': 'Vercye/outputs.md'
    - 'Architecture': 'Vercye/architecture.md'
  - 'LAI':
    - 'Getting Started': 'LAI/getting-started.md'